### ISSUE TITLE
[Address] is offline [Errno 111] Connection refused

### ISSUE THREAD

**Issue by rajeshisnepali** [TheWeirdDev/Bluetooth_Headset_Battery_Level#12]
1. Re-connecting didn't work.
2. Tried changing s.**connect((device, 4))** to **s.connect((device, 1))** or some number < **10**

**Comment by TheWeirdDev** [comment]
I've already discussed this problem in other issues. Unfortunately this script does not work with every Bluetooth headset.
I don't have a device that i can reproduce this error myself and for now it seems like there is no way to make it work.

**Comment by lesykos** [comment]
Success after SO comment hint:
1. Enter **bluetoothctl** and `disconnect 20:8B:A5:86:A7:1A`
(or via Bluetooth Devices (?))
2. `./bl_battery.py 20:8B:A5:86:A7:1A`

**Comment by rajeshisnepali** [comment]
Well, I don't know much about how the script works
 But according to the screenshot below, it reconnects twice the device to detect the battery information.

Please let me know if I'm mistaken.
One more thing, if the script had worked (without **disconnecting**), that would have been great. 

Thank you.

![bat_notify](https://user-images.githubusercontent.com/23610013/82169808-61db1500-98e2-11ea-8a8c-8f1f5922f9b2.png)

**Comment by lesykos** [comment]
In my case:
![](https://i.imgur.com/uoBFgAt.png)
