### ISSUE TITLE
No battery level for Sony WF-1000XM3

### ISSUE THREAD

**Issue by superbonaci** [TheWeirdDev/Bluetooth_Headset_Battery_Level#16]
Same issue as https://github.com/TheWeirdDev/Bluetooth_Headset_Battery_Level/issues/3:
```
./bl_battery.py <MAC>
<MAC> is offline [Errno 111] Connection refused
```

**Comment by TheWeirdDev** [comment]
I assume you tried those tricks that i mentioned?

**Comment by superbonaci** [comment]
No idea how to do it...

**Comment by TheWeirdDev** [comment]
I mean changing the port number from 4 to other numbers below 10

**Comment by superbonaci** [comment]
When testing port 6 it hangs, then trying to reconnect causes a different error:

````
./bl_battery.py <MAC>
^CTraceback (most recent call last):
  File "./bl_battery.py", line 82, in <module>
    main()
  File "./bl_battery.py", line 73, in main
    s.connect((device, 6))
KeyboardInterrupt

./bl_battery.py <MAC>
<MAC> is offline [Errno 16] Device or resource busy
````

After a while it releases the device.

**Comment by TheWeirdDev** [comment]
I can't debug because it don't have that device.

You can try putting print statements in `send` and `getATCommand` functions to see what is getting transferred between devices.
add print for `line` and `message` variables and send the output to me.

**Comment by superbonaci** [comment]
With Samsung's I tested on port 4 and does display commands, but with Sony's only get `<MAC> is offline [Errno 111] Connection refused`. The buds are connected and can play music and system audio as normal. The other ports don't work.

**Comment by TheWeirdDev** [comment]
Is your Sony device connected before running the script? someone in another issue said disconnecting the device before running the script worked for them.

**Comment by superbonaci** [comment]
Yes it's connected at the moment of running the script. With Samsung's I have no problem running the script while playing music. Will try disconnecting.

**Comment by superbonaci** [comment]
Tried again with them disconnected.
Ports 3-5 `Connection refused`.
6-7 `<MAC> is offline [Errno 115] Operation now in progress` after a while
8-9 hangs forever.

**Comment by TheWeirdDev** [comment]
Hmm, this is weird. I have no idea.

**Comment by superbonaci** [comment]
However they connect to play music or any other thing.

**Comment by Bobo1239** [comment]
Just chiming in here in case you or anybody else who owns the device wants to investigate further. To add support for the Samsung Galaxy Buds I've captured the traffic from my phone to the ear buds using the "Enable Bluetooth HCI snoop log" in the Android developer menu. (Make sure restart bluetooth afterwards for this to take effect.) Then you should be able to find the recorded traffic somewhere like `/sdcard/oem_log/btsnoop/hci_snoop_2020_05_07_19_42_35.cfa`. This file can then be analysed using Wireshark. Setting the filter to `bthfp` shows all AT commands and responses which were sent. If that results in no remaining packets then there's probably some other protocol which is used for the battery level and you'll have to look at the whole traffic.

**Comment by superbonaci** [comment]
I think I've found how battery percentage is represented. @Bobo1239 how did you send and receive AT commands, did you use Python or any other terminal software? In order do to step-by-step debub.

**Comment by Bobo1239** [comment]
In my case the AT communication already worked with the Python script from this repo and I could just go from there. For your device it seems that isn't the case unfortunately. I don't really have any experience with bluetooth so don't know why exactly you can't establish a connection.

Perhaps you can check the RFCOMM channel number which is used by Android to rule out that error. You can see it in Wireshark when selecting a captured packet and looking at the "Bluetooth RFCOMM Protocol" layer.

**Comment by superbonaci** [comment]
Can't detect which BT channel is, so here's the summary copied from Wireshark:
[Sony_WF1000XM3__Wireshark_100%vol-both.txt](https://github.com/TheWeirdDev/Bluetooth_Headset_Battery_Level/files/4617725/Sony_WF1000XM3__Wireshark_100.vol-both.txt)

Volume is specified at line 393:
```
HFP	35	Rcvd AT+IPHONEACCEV=1,1,9
```

The battery percentage value is (last_number+1)*10.
Sony WF-1000XM3 only outputs 4 different values:
1,1,9 -> 100% battery displayed (71%~100% real charge)
1,1,6 -> 70% battery displayed (51%~70% real charge)
1,1,4 -> 50% battery displayed (21%~50% real charge)
1,1,1 -> 20% battery displayed (0%~20% real charge)

The value provided by last number is the minimum value of the 2 earbuds, not counting the charging case. Example:
Left: 50%
Right: 70%
Charging case: 30%
Value displayed on phone bluetooth settings and status bar: 50%
Value received: AT+IPHONEACCEV=1,1,4

The companion app from Sony is able to provide the 3 values independently, also happens with Samsung Galaxy Buds except that those don't provide case charge:

![Sony app](https://i.imgur.com/zSJQPtr.jpg)

No idea if those values can be extracted by Wireshark or they use some proprietary encoding.

**Comment by TheWeirdDev** [comment]
I have a MI Bluetooth speaker that connects to the socket but does not send any AT command whatsoever. It sends AT commands to my phone but not to the script. I guess for some devices, it's more complicated than a simple socket connection. It would be great if a Bluetooth expert joined this conversation.

**Comment by superbonaci** [comment]
@TheWeirdDev maybe it's the bluetooth profile. I'm no bluetooth expert either.

**Comment by benjezzy** [comment]
Just wanted to mention I'm having the same issue as @superbonaci with my Sony WH-1000XM3 (over-ear headphones). Can't seem to get connect on any port. 

Anything I can do to help debug?

**Comment by kred-jon** [comment]
just stuck without result, using realme Buds Q

**Comment by superbonaci** [comment]
@kred-jon open a new issue and delete your post, this is not related.

**Comment by chaoscreater** [comment]
I can't seem to get this working on my WH-1000XM3 either. I'll be receiving my WF-1000XM3 earbuds in a few weeks, so can give that a test too. At the moment, I'm getting either a device is offline message, or that it just hangs when I test using other ports.

![image](https://user-images.githubusercontent.com/18227319/89120556-69867f00-d50b-11ea-8826-ef52038fcc34.png)

**Comment by superbonaci** [comment]
@chaoscreater forget about the script, we need a much better one like https://github.com/ThePBone/GalaxyBuds-BatteryLevel

**Comment by TheWeirdDev** [comment]
Using the port number `10` or higher might work for this device: See issue https://github.com/TheWeirdDev/Bluetooth_Headset_Battery_Level/issues/33

**If you have any comments or questions about this device or a similar Sony device, please open a new issue.**
