### ISSUE TITLE
AttributeError: module 'socket' has no attribute 'AF_BLUETOOTH'

### ISSUE THREAD

**Issue by Cris70** [TheWeirdDev/Bluetooth_Headset_Battery_Level#19]
I'm on linux OpenSUSE Tumbleweed 20200516.
When I run your script I get:
```
Traceback (most recent call last):
  File "./bl_battery.py", line 89, in <module>
    main()
  File "./bl_battery.py", line 79, in main
    with socket.socket(socket.AF_BLUETOOTH,
AttributeError: module 'socket' has no attribute 'AF_BLUETOOTH'
```
Any hint?
Thank you in advance
Cris

**Comment by TheWeirdDev** [comment]
I've already discussed this in #9.

Your python binary was built without Bluetooth support. You can install python from another repository that supports Bluetooth or compile it yourself. Make sure you have all the bluetooth libraries installed on your distro before compiling it.

**Comment by Cris70** [comment]
Thank you very much!
I'll try to grab python from another repo or to convince the maintainers to compile it with python support.

**Comment by Cris70** [comment]
Got this reply from the maintainers:

> > On 5/20/20 8:19 PM, Cris70 wrote:
> > > I'd like to request that python3 be compiled with bluetooth
> > > support, if possible.
> > >
> > > That would allow to report battery levels for bluetooth devices by
> > > using the script available
> > > at https://github.com/TheWeirdDev/FBluetooth_Headset_Battery_Level. 
> >
> > Unfortunately doing so moves bluez into the core system and creates a
> > large number of dependency cycles when trying to compile which is why
> > it isn't currently built that way.
> >
> 
> There's something like an explanation at
> https://lists.opensuse.org/opensuse-factory/2019-12/msg00133.html
> 
> It seems that Cris70 should rather be asking TheWeirdDev to update
> their script to use bluetoothd instead of directly accessing a socket.

**Comment by TheWeirdDev** [comment]
Does your python pkg contain bluetooth module?
`from bluetooth import BluetoothSocket`

**Comment by Cris70** [comment]
```
Python 3.8.2 (default, Mar 05 2020, 18:58:42) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from bluetooth import BluetoothSocket
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'bluetooth'
```

**Comment by TheWeirdDev** [comment]
Hmmm. I don't understand what they mean by 'use bluetoothd'. Do they want me to call a shell command? That will probably raise a lot of new errors.

I just grabbed python source code from the official website and it compiled and ran on my ArchLinux machine pretty easily with no dependency issue.

**Comment by Cris70** [comment]
Unfortunately I cannot help here... I am reporting what they said, but I'm not understanding it any more than you do. I had hoped it was clearer for you than it was to me :-)

**Comment by TheWeirdDev** [comment]
> ```
> Python 3.8.2 (default, Mar 05 2020, 18:58:42) [GCC] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from bluetooth import BluetoothSocket
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ModuleNotFoundError: No module named 'bluetooth'
> ```

Does this error happen again after you install this package? :
`zypper install python3-pybluez`

**Comment by Cris70** [comment]
No, I have no more errors now.
However, your script is still not working:
```
~> ./bl_battery.py A8:4D:4A:70:CF:4E
Traceback (most recent call last):
  File "./bl_battery.py", line 89, in <module>
    main()
  File "./bl_battery.py", line 79, in main
    with socket.socket(socket.AF_BLUETOOTH,
AttributeError: module 'socket' has no attribute 'AF_BLUETOOTH'
```

**Comment by TheWeirdDev** [comment]
Alright i will rewrite the script to work with pybluez

**Comment by Cris70** [comment]
Hey thank you! This is great news!

**Comment by TheWeirdDev** [comment]
I've changed the code to support pybluez and changed a few other thing as well as publishing a PyPI package.
Can you download the latest changes and try again?

**Comment by Cris70** [comment]
Done.
This is what I get when the headphones are switched off (so this is expected):
```
~/bin> ./bluetooth_battery.py A8:4D:4A:70:CF:4E
A8:4D:4A:70:CF:4E is offline [Errno 112] Host is down
```

This is when the headphones are switched on and paired and I'm listening to a song:
```
~/bin > ./bluetooth_battery.py A8:4D:4A:70:CF:4E
A8:4D:4A:70:CF:4E is offline [Errno 115] Operation now in progress
```

I have tried a lot of other combinations (not listening to anything, changing the default audio output to other hardware, etc.) but I always get this last error (Errno 115).

**Comment by TheWeirdDev** [comment]
Some users reported that they had to disconnect the device before running the script.
I start a new connection to get the battery level and some devices don't accept new connections when they are already connected.

**Comment by Cris70** [comment]
Tried by disconnecting first. As soon as I launch your script the headphones reconnect, and after a while I get the same error as before. When your script ends, the headphones disconnect briefly and then reconnect.

**Comment by TheWeirdDev** [comment]
Did you try other port numbers? ([mentioned here](https://github.com/TheWeirdDev/Bluetooth_Headset_Battery_Level/blob/master/Readme.md))

**Comment by Cris70** [comment]
You got it!
Trying with port number 1 led to success:
```
~/bin> ./bluetooth_battery.py A8:4D:4A:70:CF:4E.1
Battery level for A8:4D:4A:70:CF:4E is 100%
```
And I didn't even have to disconnect first. Also, sound play is not interrupted when running your script.

My headphones: AUKEY EP-T21 ... just in case you want to set up a database of hardware that works (with correct port numbers).
