### ISSUE TITLE
Detect whether battery percentage or dock state is received

### ISSUE THREAD

**Issue by kescherCode** [TheWeirdDev/Bluetooth_Headset_Battery_Level#2]
As the percentage might be wrong when a dock state is received, perhaps there is a way to just error out in this case?

**Comment by TheWeirdDev** [comment]
In that case it just needs to parse (key,value) pairs and read the percentage when the key '1' is found.

I'm not sure if this happens or not. The "Apple Accessory Design Guidelines" says it could happen. I will fix this later as it's probably not a big problem.

**Comment by TheWeirdDev** [comment]
Should be fixed
