### ISSUE TITLE
Compatible with Mac OS X?

### ISSUE THREAD

**Issue by JCsplash** [TheWeirdDev/Bluetooth_Headset_Battery_Level#20]
@TheWeirdDev Does this library work on Mac? I'm getting "module 'socket' has no attribute 'AF_BLUETOOTH'"

It seems like there's no easy way to install python with bluetooth support on mac os x or install libbluetooth-dev. Any help would be much appreciated!

**Comment by TheWeirdDev** [comment]
After googling some stuff i didn't find anything. I guess python doesn't support this on MacOS.
I would like to test and research on this but i neither have a Mac nor know how it works.

Doesn't Mac OS already have this feature included?

This project might be useful as well: https://github.com/jariz/Akku

**Comment by JCsplash** [comment]
I know it's possible to get battery levels for Apple devices (AirPods, Beats, iPhones/iPads..etc). 

I'm not sure if it's possible to get battery levels for non-apple headsets like Bose QC35s.

Akku seems helpful but i'm hoping for a simpler solution, ideally a program that can quickly get headset charge via command line.

**Comment by TheWeirdDev** [comment]
Since python standard library doesn't have this on mac, i'm sorry to say that there is nothing i can do.
Maybe we find a solution in future.

**Comment by TheWeirdDev** [comment]
Hi again. I switched to PyBluez library and it claims to support MacOS and Windows. Would you mind testing it out?

**Comment by JCsplash** [comment]
@TheWeirdDev Thanks for integrating PyBluez! Just tried the new version but am getting IOServiceOpen() Error
```
2020-05-24 00:00:52.001 Python[51048:4141490] [establishKernelConnection] Received an error from IOServiceOpen() - 0xe00002c7.  NULLing out io_service_t.
2020-05-24 00:00:53.017 Python[51048:4141490] instantiateOnDevice for regular
```

Have you seen this before?

**Comment by TheWeirdDev** [comment]
Seems like a warning. It should have worked.

how did you install pybluez? maybe it's not compatible with your macos version. Installing it from somewhere else might work.

**Comment by JCsplash** [comment]
I used ``` pip3 install PyBluez ``` Im pretty sure it installed correctly. When i run PyBluez's example code though, I still get 0 devices found.

```
nearby_devices = bluetooth.discover_devices(lookup_names=True)
print("Found {} devices.".format(len(nearby_devices)))
```

Let me know if you have any troubleshooting ideas.

**Comment by JCsplash** [comment]
Just noticed when i use the correct channel (#8 for me), my headphones don't disconnect immediately. But im still unable to get the battery level. Don't think the original warning i posted has anything to do with it though.

**Comment by JCsplash** [comment]
@TheWeirdDev I confirmed the following part is working.

```
s = bluetooth.BluetoothSocket(bluetooth.RFCOMM)
                s.connect((device, port))
```

The problem is at ``` s.recv(128) ``` in ``` getATCommand(s, s.recv(128), device) ```

The code just hangs indefinitely. Any idea what's going on here?

**Comment by TheWeirdDev** [comment]
I have a bt speaker that does the same thing. Still haven't figured out why.

**Comment by JCsplash** [comment]
Yeah I tried my airpods as well and am getting the same result. Another problem is that s.close() will disconnect the device from the computer. Hope we can figure that out too.

Let me know if you find out any more info.

**Comment by TheWeirdDev** [comment]
Calling close is just a good practice, Python will close the socket before exiting the script anyway.
