### ISSUE TITLE
ModuleNotFoundError bluetooth

### ISSUE THREAD

**Issue by superbonaci** [TheWeirdDev/Bluetooth_Headset_Battery_Level#22]
On ubuntu 20.04
```
python3 bluetooth_battery.py 
Traceback (most recent call last):
  File "bluetooth_battery.py", line 12, in <module>
    import bluetooth
ModuleNotFoundError: No module named 'bluetooth'
```

**Comment by TheWeirdDev** [comment]
The answer is in the description:
> make sure you have `python-pybluez` or `python3-pybluez` installed on your system. if you are using pip, install `PyBluez` instead.

**Comment by superbonaci** [comment]
Fixed
```
sudo apt install python3-bluez
```

**Comment by superbonaci** [comment]
Please add to Readme.md

**Comment by TheWeirdDev** [comment]
It already is :|

**Comment by superbonaci** [comment]
> It already is :|

The `python3-bluez` specifically is not mentioned. Would be really helpful.

**Comment by TheWeirdDev** [comment]
Ok. I added it.

**Comment by superbonaci** [comment]
Thanks, typo:
`python3-bluz` is `python3-bluez`

**Comment by TheWeirdDev** [comment]
Thanks. Fixed.
