### ISSUE TITLE
Read Samsung Galaxy Buds advanced and proprietary values

### ISSUE THREAD

**Issue by superbonaci** [TheWeirdDev/Bluetooth_Headset_Battery_Level#25]
A developer has released a software which can read all advanced/proprietary values for the Samsung Galaxy Buds, including detailed battery levels and more. I wonder if the translation from .NET to Python can be done for Linux.

There is so much information that can be obtained.

https://github.com/ThePBone/GalaxyBudsClient

**Comment by TheWeirdDev** [comment]
This task needs someone that owns Samsung Galaxy Buds and can dedicate his/her time and effort to make it work.

**Comment by superbonaci** [comment]
So it's not that easy to translate the RFcomm protocol?

**Comment by TheWeirdDev** [comment]
Seems like they are using a [customized protocol](https://github.com/ThePBone/GalaxyBudsClient/blob/master/Galaxy%20Buds%20Client/message/SPPMessage.cs).
I don't know anything about .Net but it should be cross platform. The easier option would be porting the existing code to make it work on Linux.
You can ask the original developer.

**Comment by superbonaci** [comment]
Could be possible to get each bud individual battery using Python reading the bytes mentioned here:
https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=16615

**Comment by superbonaci** [comment]
@ThePBone made a great python script which already does that: https://github.com/ThePBone/GalaxyBudsClient/issues/8
