### ISSUE TITLE
Script freeze without result. [realme Buds Q]

### ISSUE THREAD

**Issue by kred-jon** [TheWeirdDev/Bluetooth_Headset_Battery_Level#29]
Hello,
Success install it under Ubuntu 20.04, using realme Buds Q. However, after run the scripts its freeze without result until stop it manually. Its feedback with below error.

^CTraceback (most recent call last):
  File "./bluetooth_battery", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.8/site-packages/bluetooth_battery/bluetooth_battery.py", line 81, in main
    while getATCommand(s, s.recv(128), device):
  File "<string>", line 3, in recv
KeyboardInterrupt

Hopefully can help me to solve it.

Thanks

**Comment by kred-jon** [comment]
Additional info from bluez:

Name: realme Buds Q
	Alias: realme Buds Q
	Class: 0x00240404
	Icon: audio-card
	Paired: yes
	Trusted: yes
	Blocked: no
	Connected: yes
	LegacyPairing: no
	UUID: Serial Port               (00001101-0000-1000-8000-00805f9b34fb)
	UUID: Audio Sink                (0000110b-0000-1000-8000-00805f9b34fb)
	UUID: A/V Remote Control Target (0000110c-0000-1000-8000-00805f9b34fb)
	UUID: Advanced Audio Distribu.. (0000110d-0000-1000-8000-00805f9b34fb)
	UUID: A/V Remote Control        (0000110e-0000-1000-8000-00805f9b34fb)
	UUID: Handsfree                 (0000111e-0000-1000-8000-00805f9b34fb)

**Comment by kred-jon** [comment]
Packet Sniff: 

**host	controller	HCI_CMD	7	Sent Read Tx Power Level**

Frame 25: 7 bytes on wire (56 bits), 7 bytes captured (56 bits) on interface bluetooth0, id 0
    Interface id: 0 (bluetooth0)
        Interface name: bluetooth0
    Encapsulation type: Bluetooth H4 with linux header (99)
    Arrival Time: Jul 15, 2020 15:51:01.323820000 +08
    [Time shift for this packet: 0.000000000 seconds]
    Epoch Time: 1594799461.323820000 seconds
    [Time delta from previous captured frame: 0.000047000 seconds]
    [Time delta from previous displayed frame: 0.000047000 seconds]
    [Time since reference or first frame: 3.029900000 seconds]
    Frame Number: 25
    Frame Length: 7 bytes (56 bits)
    Capture Length: 7 bytes (56 bits)
    [Frame is marked: False]
    [Frame is ignored: False]
    Point-to-Point Direction: Sent (0)
    [Protocols in frame: bluetooth:hci_h4:bthci_cmd]
Bluetooth
    [Source: host]
    [Destination: controller]
Bluetooth HCI H4
    [Direction: Sent (0x00)]
    HCI Packet Type: HCI Command (0x01)
Bluetooth HCI Command - Read Tx Power Level
    Command Opcode: Read Tx Power Level (0x0c2d)
        0000 11.. .... .... = Opcode Group Field: Host Controller & Baseband Commands (0x03)
        .... ..00 0010 1101 = Opcode Command Field: Read Tx Power Level (0x02d)
    Parameter Total Length: 3
    Connection Handle: 0x000b
    Tx Power Level Type: Current Tx Power Level (0x00)
    [Response in frame: 26]
    [Command-Response Delta: 0.327ms]


**controller	host	HCI_EVT	10	Rcvd Command Complete (Read Tx Power Level)**

Frame 26: 10 bytes on wire (80 bits), 10 bytes captured (80 bits) on interface bluetooth0, id 0
    Interface id: 0 (bluetooth0)
        Interface name: bluetooth0
    Encapsulation type: Bluetooth H4 with linux header (99)
    Arrival Time: Jul 15, 2020 15:51:01.324147000 +08
    [Time shift for this packet: 0.000000000 seconds]
    Epoch Time: 1594799461.324147000 seconds
    [Time delta from previous captured frame: 0.000327000 seconds]
    [Time delta from previous displayed frame: 0.000327000 seconds]
    [Time since reference or first frame: 3.030227000 seconds]
    Frame Number: 26
    Frame Length: 10 bytes (80 bits)
    Capture Length: 10 bytes (80 bits)
    [Frame is marked: False]
    [Frame is ignored: False]
    Point-to-Point Direction: Received (1)
    [Protocols in frame: bluetooth:hci_h4:bthci_evt]
Bluetooth
    [Source: controller]
    [Destination: host]
Bluetooth HCI H4
    [Direction: Rcvd (0x01)]
    HCI Packet Type: HCI Event (0x04)
Bluetooth HCI Event - Command Complete
    Event Code: Command Complete (0x0e)
    Parameter Total Length: 7
    Number of Allowed Command Packets: 1
    Command Opcode: Read Tx Power Level (0x0c2d)
        0000 11.. .... .... = Opcode Group Field: Host Controller & Baseband Commands (0x03)
        .... ..00 0010 1101 = Opcode Command Field: Read Tx Power Level (0x02d)
    Status: Success (0x00)
    Connection Handle: 0x000b
    Transmit Power Level (dBm): 6
    [Command in frame: 25]
    [Command-Response Delta: 0.327ms]

**Comment by obbardc** [comment]
same with pxc550

**Comment by kred-jon** [comment]
Here in mobile the battery status is available.

![IMG_3978](https://user-images.githubusercontent.com/38023611/88001874-b8a7d980-cb33-11ea-997a-96cf1b19e6bf.jpg)

**Comment by kred-jon** [comment]
OK! great news!! i got the result after trying many port: 
![image](https://user-images.githubusercontent.com/38023611/89391871-5823b980-d73b-11ea-8654-8f9ef13bbc84.png)

**Comment by TheWeirdDev** [comment]
I'm glad it worked. Thanks to https://github.com/TheWeirdDev/Bluetooth_Headset_Battery_Level/issues/33 for figuring it out.

**Comment by TheWeirdDev** [comment]
I have updated the code to find the port number automatically. Can you try the latest version without specifying the port number to see if it works?

**Comment by kred-jon** [comment]
yeph! success not, its perfect! :+1: 

![image](https://user-images.githubusercontent.com/38023611/89477844-dd04e680-d7c0-11ea-94ec-2414dc15a49e.png)

It should be the plugins for BlueMan now.

Thank You.

**Comment by kred-jon** [comment]
i have success make it as gnome-shell extension, and tuning up your script too.

![image](https://user-images.githubusercontent.com/38023611/89499626-e5761500-d7f2-11ea-8305-8411a9b770ea.png)

**Comment by TheWeirdDev** [comment]
Cool! That's a great use case for it.

**Comment by obbardc** [comment]
getting this in blueman to show on the BT icon would be great...

**Comment by denisgolius** [comment]
> i have success make it as gnome-shell extension, and tuning up your script too.
> 
> ![image](https://user-images.githubusercontent.com/38023611/89499626-e5761500-d7f2-11ea-8305-8411a9b770ea.png)

Could you share it with us? I'm using xfce but how knows maybe I'll switch to gnome ...
