### ISSUE TITLE
Does not work with Samsung Galaxy Buds

### ISSUE THREAD

**Issue by superbonaci** [TheWeirdDev/Bluetooth_Headset_Battery_Level#3]
When entering the command with mac address process keeps waiting without any output.

**Comment by TheWeirdDev** [comment]
Try changing the port number in [line 56](https://github.com/TheWeirdDev/Bluetooth_Headset_Battery_Level/blob/5a899b4af56f52326c69fdad54d80e01fa2a9104/bl_battery.py#L56) from 4 to 3.
If it didn't work, try other numbers below 10. The port number is probably varied from one headset to another.

**Comment by superbonaci** [comment]
With 4,3 and 2 same thing. 1, 0 and above 4 says `ConnectionRefusedError: [Errno 111] Connection refused`

**Comment by TheWeirdDev** [comment]
I assume your device does not support communication through AT commands. But to be sure, you can use this debug script to see if it outputs any useful info:

https://github.com/clst/Bluetooth_Headset_Battery_Level

**Comment by superbonaci** [comment]
It does not show any debug, with the exception that connect earphones to computer yet can't hear sound through them. I have to disconnect and reconnect again from KDE system settings to be able to hear.

**Comment by TheWeirdDev** [comment]
Well, unfortunately your device is not compatible with this protocol and there's nothing to be done about it. I'm closing this.

**Comment by Bobo1239** [comment]
Hm, I also have Samsung Galaxy Buds and I'm at least able to see some AT communication (port 4):
```
AT+BRSF=923
  +BRSF:20
  OK
AT+CIND=?
  +CIND: ("battchg",(0-5))
  OK
AT+CIND?
  +CIND: 5
  OK
AT+CMER=3,0,0,1
  OK
AT+VGM=7
  OK
AT+VGS=8
  OK
AT+CCWA=1
  OK
AT+SAMSUNG=VID,117,PID,40977,BTVER,R170XXU0ATD3
  OK
AT+SAMSUNG=VR_BTN,0
  OK
```
Unfortunately it just stops there. Any idea what's going wrong?

**Comment by TheWeirdDev** [comment]
Seems like Samsung is sending samsung-specific commands. I don't know what it expects to receive or even if it expects to receive anything.

I haven't found any info or documentation about these commands.

**Comment by superbonaci** [comment]
@TheWeirdDev is there any way I can debug this, for example using android, to see what it sends and receives?

**Comment by TheWeirdDev** [comment]
> @TheWeirdDev is there any way I can debug this, for example using android, to see what it sends and receives?

The latest pull request by @Bobo1239 claims that it adds support for Samsung galaxy buds. Have you tried pulling the new changes and check it again?

**Comment by superbonaci** [comment]
@TheWeirdDev not yet, cheking in a moment.

**Comment by superbonaci** [comment]
Finally tested, works perfect. Thank you very much.
