### ISSUE TITLE
Collect known devices and their respective settings

### ISSUE THREAD

**Issue by balsoft** [TheWeirdDev/Bluetooth_Headset_Battery_Level#32]
Awesome script!

However, it's quite cumbersome to set up for use with multiple devices, each of which may need a different port, or may need some other hacks (like #23). Perhaps it would be a good idea to collect a list of such known devices and their settings somewhere, and then use that list to figure out what to do? The obvious place to put it would be here, in this repo.

**Comment by TheWeirdDev** [comment]
I'm using bash aliases for my different devices and it's pretty easy to use.

Those other hacks should be done manually. Doing them programmatically might introduce new dependencies which i'm trying to avoid.

**Comment by balsoft** [comment]
> Those other hacks should be done manually

Ok, I disagree with this wholeheartedly, but you're the author so you can do whatever. maybe this belongs in a separate project then. Thanks for the explanation anyways.

**Comment by TheWeirdDev** [comment]
I would implement this but only if there is a way to disconnect the device in Python with PyBluez. Adding new dependencies or running shell commands in the script might introduce a lot of new problems. I'll make an experimental branch if i find any useful info.
