### ISSUE TITLE
Connection Refused [Ubuntu 19.10] [JBL T450BT]

### ISSUE THREAD

**Issue by adilsaju** [TheWeirdDev/Bluetooth_Headset_Battery_Level#4]
I've been getting this traceback while running:
```
adil@adil-GL552JX:~/Bluetooth_Headset_Battery_Level$ ./bl_battery.py 30:C0:1B:E9:55:DB
Traceback (most recent call last):
  File "./bl_battery.py", line 62, in <module>
    main()
  File "./bl_battery.py", line 56, in main
    s.connect((BT_ADDRESS, 4))
ConnectionRefusedError: [Errno 111] Connection refused
adil@adil-GL552JX:~/Bluetooth_Headset_Battery_Level$ sudo ./bl_battery.py 30:C0:1B:E9:55:DB
[sudo] password for adil: 
Traceback (most recent call last):
  File "./bl_battery.py", line 62, in <module>
    main()
  File "./bl_battery.py", line 56, in main
    s.connect((BT_ADDRESS, 4))
ConnectionRefusedError: [Errno 111] Connection refused

```
Tried with and without sudo.

**Comment by TheWeirdDev** [comment]
There is no need for sudo. Try changing the port number in [line #56](https://github.com/TheWeirdDev/Bluetooth_Headset_Battery_Level/blob/master/bl_battery.py#L56) from 4 to 3 or maybe other numbers below 10.

**Comment by victor-oliveira1** [comment]
Hey dude!

Just change **s.connect((device, 4))** to **s.connect((device, 1))** on line 59.

Tks!

**Comment by jsilduarte** [comment]
This might be something else entirely, but I've found a different scenario in which a "Connection refused" error happens. I couldn't get the script to work so I borrowed a different pair of headphones to test the script.

On one device (the borrowed one), running the script while the device is connected and playing works fine and returns the battery level.

On a different device (the one I was trying to get to work first), trying to run the script while the device is connected and playing returns "Connection refused". I then tried to disconnect that device and run the script again and it worked. What I take from this is that some devices simply don't allow a second connection and using this script successfully requires running it from a disconnected state.

**Comment by superbonaci** [comment]
Which bluetooth device is the one that fails?

**Comment by arjvik** [comment]
@jduar I encountered a similar problem just now - running it while using my headphones didn't work and gave the connection regused error. I tried disconnecting my headphones, stopping my music, and reconnecting, and as expected the command worked. However, I then started my music again and _the command continued to work!_

I am completely baffled at how that works... but I guess I shouldn't question it :)

I was actually planning on making this a module in my bar, however it seems that the headset makes a loud annoying beep every time the script connects to read the battery level, so I really can't run it periodically.

**Comment by shanmukhateja** [comment]
@arjvik This is because this script establishes a socket connection to the bluetooth headset and the headsets are programmed to give out a "beep" or an audio clip informing the headset state:

In my boAt headset, it says "You're now connected to boAt Rockerz" when the script is run as the script disconnects, this is followed by "Disconnected" audio clip from the headset.

The trivial solution would be get a hold on the socket object which Ubuntu uses to communicate with the headset and grab the battery level which is usually handled by `PulseAudio` but that is complicated.

**Comment by superbonaci** [comment]
@shanmukhateja Ubuntu does not read any battery level from any headset.

**Comment by shanmukhateja** [comment]
@superbonaci Yes, you are correct. Ubuntu doesn't read battery level for any headset. I never said it did :\

**Comment by superbonaci** [comment]
@shanmukhateja since you mentioned that `PulseAudio` can read battery level from headsets... What were you referring to?

**Comment by shanmukhateja** [comment]
I was referring to an open feature request for supporting this very feature at PulseAudio on GitLab issue no. 722. 

There's also a prototype daemon which can read a headset battery level in the issue page.

CAUTION: IT'S FOR ADVANCED USERS WHO KNOW HOW TO FIX STUFF WHEN IT BREAKS!

**Comment by superbonaci** [comment]
There are several protocols and commands for bluetooth operation. We come from a segmented world where each manufacturer uses its own combination of software+hardware, so will take some time to get it working.
[Support battery level indication over HFP](https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/722)

Like the battery issue, there's also the volume issue:
[AVRCP volume reporting for A2DP profile](https://gitlab.freedesktop.org/pulseaudio/pulseaudio/issues/724)

The bluetooth thing still needs some serious development.

**Comment by adilsaju** [comment]
> There is no need for sudo. Try changing the port number in [line #73](https://github.com/TheWeirdDev/Bluetooth_Headset_Battery_Level/blob/master/bl_battery.py#L73) from 4 to 3 or maybe other numbers below 10.
> 
> EDIT:
> No need to edit the file. You can now set the port number. Read the main page for instructions.

Thank you. Changed the port number to 1. And it worked!!

**Comment by Kronodile** [comment]
> Hey dude!
> 
> Just change **s.connect((device, 4))** to **s.connect((device, 1))** on line 59.
> 
> Tks!

Thanks! This worked for me
