### ISSUE TITLE
Protocol not supported error when BT_RFCOMM is in the kernel config

### ISSUE THREAD

**Issue by devsk** [TheWeirdDev/Bluetooth_Headset_Battery_Level#44]
$ bluetooth_battery AC:12:2F:0B:3D:84
Couldn't find the RFCOMM port number
Traceback (most recent call last):
  File "/home/devsk/.local/bin/bluetooth_battery", line 33, in <module>
    sys.exit(load_entry_point('bluetooth-battery==1.2.0', 'console_scripts', 'bluetooth_battery')())
  File "/home/devsk/.local/lib/python3.7/site-packages/bluetooth_battery/bluetooth_battery.py", line 90, in main
    s = bluetooth.BluetoothSocket(bluetooth.RFCOMM)
  File "/home/devsk/.local/lib/python3.7/site-packages/bluetooth/bluez.py", line 165, in __init__
    _sock = _bt.btsocket (proto)
_bluetooth.error: (93, 'Protocol not supported')

$ zgrep RFCOMM /proc/config.gz 
CONFIG_BT_RFCOMM=y
CONFIG_BT_RFCOMM_TTY=y

Running Gentoo Linux with kernel 5.10.2

$ bluetoothctl devices
Device AC:12:2F:0B:3D:84 Soundcore Life Q30

**Comment by TheWeirdDev** [comment]
Is `rfcomm` kernel module loaded at startup?

**Comment by devsk** [comment]
As you can see from the zgrep I posted, the module is built into the kernel. So, its loaded for sure.

**Comment by TheWeirdDev** [comment]
Just to make sure, what is the output of `lsmod | grep rfcomm`

**Comment by devsk** [comment]
If a module is built-in, it won't show up in lsmod. In fact, it just doesn't exist as a .ko file that you can modprobe or insmod to load it.

# modprobe rfcomm
modprobe: FATAL: Module rfcomm not found in directory /lib/modules/5.10.2

# lsmod|grep -i rfcom

$ zgrep RFCOMM /proc/config.gz
CONFIG_BT_RFCOMM=y
CONFIG_BT_RFCOMM_TTY=y

**Comment by atomsymbol** [comment]
> If a module is built-in, it won't show up in lsmod. In fact, it just doesn't exist as a .ko file that you can modprobe or insmod to load it.
> 
> ```
> # modprobe rfcomm
> modprobe: FATAL: Module rfcomm not found in directory /lib/modules/5.10.2
> 
> # lsmod|grep -i rfcom
> 
> $ zgrep RFCOMM /proc/config.gz
> CONFIG_BT_RFCOMM=y
> CONFIG_BT_RFCOMM_TTY=y
> ```

This is a bug in the Linux kernel. Try `CONFIG_BT_RFCOMM=m`.

**Comment by devsk** [comment]
Do you have a link for the bug?

How is bluetooth working if there is a bug with basic RFCOMM protocol missing? I can see and connect all devices fine. blueman has no issues.

**Comment by TheWeirdDev** [comment]
> This is a bug in the Linux kernel. Try `CONFIG_BT_RFCOMM=m`.

Now that makes sense since my arch machine also has `CONFIG_BT_RFCOMM` set to `m` by default.
```
➜ zgrep RFCOMM /proc/config.gz
CONFIG_BT_RFCOMM=m
CONFIG_BT_RFCOMM_TTY=y
```

**Comment by atomsymbol** [comment]
> Do you have a link for the bug?
> 
> How is bluetooth working if there is a bug with basic RFCOMM protocol missing? I can see and connect all devices fine. blueman has no issues.

I haven't investigated this issue further. I only know that when I recompiled kernel with the following options then I see a "Protocol not supported" message:

    CONFIG_BT_RFCOMM=y
    CONFIG_BT_BNEP=y
    CONFIG_BT_HIDP=y

**Comment by devsk** [comment]
ok, that's evidence.

Do we need to make the other two  (HIDP and BNEP) also as modules?

**Comment by atomsymbol** [comment]
> Do we need to make the other two (HIDP and BNEP) also as modules?

I don't know.

**Comment by TheWeirdDev** [comment]
Mine is like this: (I didn't change these)

```
➜ zgrep BT_BNEP /proc/config.gz
CONFIG_BT_BNEP=m
CONFIG_BT_BNEP_MC_FILTER=y
CONFIG_BT_BNEP_PROTO_FILTER=y

➜ zgrep BT_HIDP /proc/config.gz
CONFIG_BT_HIDP=m
23:17:40 alireza ~ ➜ 
```

**Comment by devsk** [comment]
I can confirm. This is a weird kernel bug. It works when RFCOMM=m is selected.

Closing this because its not this program's fault.
