### ISSUE TITLE
apple air pods

### ISSUE THREAD

**Issue by mrsteve0924** [TheWeirdDev/Bluetooth_Headset_Battery_Level#57]
cant seem to get info for apple air pods
just hangs. following errors

root@ArchMan ~ # bluetooth_battery.py 14:88:E6:B5:47:2E.7
Traceback (most recent call last):
  File "/root/.bin/bluetooth_battery.py", line 119, in <module>
    main()
  File "/root/.bin/bluetooth_battery.py", line 111, in main
    while get_at_command(sock, sock.recv(128), device):
  File "<string>", line 3, in recv

**Comment by TheWeirdDev** [comment]
Apple AirPods use a proprietary protocol for communicating with other Apple products. This project won't support it, but there are other projects that have successfully implemented it:

[AirStatus](https://github.com/delphiki/AirStatus) + [Gnome Extension](https://github.com/delphiki/gnome-airpods-battery-status)
[apodsmon](https://github.com/slp/apodsmon)
