### ISSUE TITLE
Gnome 40

### ISSUE THREAD

**Issue by Fen0day** [TheWeirdDev/Bluetooth_Headset_Battery_Level#61]
Would be good if u create version for gnome 40. Is there any plans?

**Comment by TheWeirdDev** [comment]
I didn't create that extension and I don't maintain it. It has its own maintainer and GitHub repository. Go ask them:
https://extensions.gnome.org/extension/3991/bluetooth-battery/

**Comment by Fen0day** [comment]
> I didn't create that extension and I don't maintain it. It has its own maintainer and GitHub repository. Go ask them:
> https://github.com/MichalW/gnome-bluetooth-battery-indicator

oh, thanks you anyway
