### ISSUE TITLE
Apple Air Pods Pro

### ISSUE THREAD

**Issue by artemcodes** [TheWeirdDev/Bluetooth_Headset_Battery_Level#72]
Can't get information for Apple Airpods Pro. Doesn't output anything.

The extension [gnome-airpods-battery-status](https://github.com/delphiki/gnome-airpods-battery-status) just shows a percent sign

Ubuntu 20.04

**Comment by TheWeirdDev** [comment]
AirPods use a different protocol. I don't think this script will ever support that. You can search for other projects on GitHub that were written specifically for AirPods.
