### ISSUE TITLE
Bluetooth Device offline

### ISSUE THREAD

**Issue by ITCMD** [TheWeirdDev/Bluetooth_Headset_Battery_Level#8]
OS: Lubuntu with latest updates
Bluetooth device: iHome speaker

When I run your script it gives the following output:
```
$lucas:~$ ./bl_battery.py FC:58:FA:EA:74:FC
FC:58:FA:EA:74:FC is offline
```
However the device is certainly online, I'm playing music from it now. Here it is on here:
![Blueman Wiz](https://i.imgur.com/nlmR9zu.png)

Any ideas why this is happening?

**Comment by TheWeirdDev** [comment]
Disconnect the device then run the script again. Does it show the same error?

**Comment by ITCMD** [comment]
No. When I disconnect it waits for a while and tells me it cannot connect, or something. I can give you the exact message if you would like.

**Comment by dorianneto** [comment]
OS: Debian 10.3
Bluetooth device: PaMu Slide (Bluetooth Earphone)

I'm facing the same problem here :/

> Disconnect the device then run the script again. Does it show the same error?

I did this but still doesn't work.

**Comment by TheWeirdDev** [comment]
This fork of the project prints the debug logs: https://github.com/clst/Bluetooth_Headset_Battery_Level

You can try it and send me the output.

**Comment by ITCMD** [comment]
will do thanks @TheWeirdDev

**Comment by dorianneto** [comment]
The output:
```
Traceback (most recent call last):
  File "bl_battery.py", line 64, in <module>
    main()
  File "bl_battery.py", line 58, in main
    s.connect((BT_ADDRESS, 3))
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by TheWeirdDev** [comment]
> The output:
> 
> ```
> Traceback (most recent call last):
>   File "bl_battery.py", line 64, in <module>
>     main()
>   File "bl_battery.py", line 58, in main
>     s.connect((BT_ADDRESS, 3))
> ConnectionRefusedError: [Errno 111] Connection refused
> ```

You can try changing the port number in line `s.connect((BT_ADDRESS, 3))` from 3 to other numbers (0 to 9) and check if that works. Because it is device specific and varies from device to device. 
If that didn't work either, your device is unsupported.

**Comment by QkiZMR** [comment]
I checked numbers from 0 to 9. Nothing worked.

**Comment by TheWeirdDev** [comment]
> I checked numbers from 0 to 9. Nothing worked.

Your device does not support this protocol.

**Comment by QkiZMR** [comment]
Which protocol? Showing battery status? I'm using JBL E45BT. When I connect it to Android phone I see percentage of power in headphones battery.

**Comment by TheWeirdDev** [comment]
> Which protocol? Showing battery status? I'm using JBL E45BT. When I connect it to Android phone I see percentage of power in headphones battery.

This script uses AT commands to communicate with Bluetooth devices. Some devices support this commands, some don't.
If your headset uses a different way to communicate, you have to find another way to check battery status. I can't help you with that.

**Comment by TheWeirdDev** [comment]
Closed due to the inactivity
