### ISSUE TITLE
Why BatteryStateQuerier send messaged to sock?

### ISSUE THREAD

**Issue by steam3d** [TheWeirdDev/Bluetooth_Headset_Battery_Level#89]
I tested code cycle:
https://github.com/TheWeirdDev/Bluetooth_Headset_Battery_Level/blob/e74acb74b60bb744347a4cbc7d784918040652a7/bluetooth_battery.py#L103

If I do not send any command back, I will receive the same result. So why do you send some commands like this?

https://github.com/TheWeirdDev/Bluetooth_Headset_Battery_Level/blob/e74acb74b60bb744347a4cbc7d784918040652a7/bluetooth_battery.py#L123

**Comment by TheWeirdDev** [comment]
Your device sends the same result but other people's do not. Some commands have been added to maximize the support for multiple devices and might not be needed for your device.

Some Bluetooth devices will ask if some feature is supported or not and only answer if we say we support it. We use the commands we captured from Bluetooth traffic of android devices and try to respond like a real device.
