### ISSUE TITLE
AttributeError: module 'socket' has no attribute 'AF_BLUETOOTH'

### ISSUE THREAD

**Issue by iuryfukuda** [TheWeirdDev/Bluetooth_Headset_Battery_Level#9]
When i tried to execute script, i got this message.
```
    s = socket.socket(socket.AF_BLUETOOTH,
AttributeError: module 'socket' has no attribute 'AF_BLUETOOTH'
```

you know any solution for this?

i believe is some about my system config, but i can't find anything about this, i can isolate the problem using:
```
$ python -c "import socket; socket.AF_BLUETOOTH"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'socket' has no attribute 'AF_BLUETOOTH'
```

Thhank's for project, is really useful

**Comment by TheWeirdDev** [comment]
What is your operating system? What python version are you using?

**Comment by iuryfukuda** [comment]
OS void linux:
```
$ uname -srvmo
Linux 5.4.27_1 #1 SMP PREEMPT Sat Mar 21 09:34:54 UTC 2020 x86_64 GNU/Linux
```
Python version:
```
$ python --version
Python 3.8.2
```

**Comment by TheWeirdDev** [comment]
Seems like your python binary was built without Bluetooth socket support. You need to install python from another repository or the official website.

**Comment by iuryfukuda** [comment]
You're right, i just download and compile the site version, and works like a spell.

Thank you very much.

**Comment by bit-man** [comment]
For [Python3 bluetooth support is not installed](https://stackoverflow.com/questions/29107537/missing-socket-af-bluetooth-in-anaconda-python#comment46475491_29108576) unless  `libbluetooth-dev` package is installed as well

**Comment by TheWeirdDev** [comment]
The new version doesn't require `AF_BLUETOOTH` and uses `PyBluez` library instead. No one will encounter this issue should again.
